"""initial mvp0 schema

Revision ID: b9387d80d7b1
Revises: 
Create Date: 2026-05-12 22:45:40.343026+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9387d80d7b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('area_atuacao', sa.String(), nullable=True),
    sa.Column('last_login_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_username', ['username'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_display_name', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('metadata', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('previous_hash', sa.String(), nullable=True),
    sa.Column('record_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_action', ['action'], unique=False)
        batch_op.create_index('idx_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_audit_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('idx_audit_user', ['user_id'], unique=False)

    op.create_table('cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('procedure_number', sa.String(), nullable=True),
    sa.Column('fact_date', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('responsible', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_code')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index('idx_cases_case_code', ['case_code'], unique=False)
        batch_op.create_index('idx_cases_name', ['name'], unique=False)
        batch_op.create_index('idx_cases_status', ['status'], unique=False)

    op.create_table('persons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('aliases', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('rg', sa.String(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('mother_name', sa.String(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('reliability_level', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.create_index('idx_persons_aliases', ['aliases'], unique=False)
        batch_op.create_index('idx_persons_cpf', ['cpf'], unique=False)
        batch_op.create_index('idx_persons_full_name', ['full_name'], unique=False)
        batch_op.create_index('idx_persons_status', ['status'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('value_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('editable_by_operator', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('case_person_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role_in_case', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('reliability_level', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'person_id', 'role_in_case', name='uq_case_person_role')
    )
    with op.batch_alter_table('case_person_links', schema=None) as batch_op:
        batch_op.create_index('idx_cpl_case', ['case_id'], unique=False)
        batch_op.create_index('idx_cpl_person', ['person_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_person_links', schema=None) as batch_op:
        batch_op.drop_index('idx_cpl_person')
        batch_op.drop_index('idx_cpl_case')

    op.drop_table('case_person_links')
    op.drop_table('settings')
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index('idx_persons_status')
        batch_op.drop_index('idx_persons_full_name')
        batch_op.drop_index('idx_persons_cpf')
        batch_op.drop_index('idx_persons_aliases')

    op.drop_table('persons')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index('idx_cases_status')
        batch_op.drop_index('idx_cases_name')
        batch_op.drop_index('idx_cases_case_code')

    op.drop_table('cases')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_user')
        batch_op.drop_index('idx_audit_timestamp')
        batch_op.drop_index('idx_audit_entity')
        batch_op.drop_index('idx_audit_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_username')

    op.drop_table('users')
    # ### end Alembic commands ###
