"""sprint01b organizations and org links

Revision ID: 5bfc47957379
Revises: b9387d80d7b1
Create Date: 2026-08-02 02:17:11.902535+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bfc47957379'
down_revision: Union[str, None] = 'b9387d80d7b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('siglas', sa.String(), nullable=True),
    sa.Column('alcunhas', sa.String(), nullable=True),
    sa.Column('org_type', sa.String(), nullable=True),
    sa.Column('area_atuacao', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('reliability_level', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index('idx_org_name', ['name'], unique=False)
        batch_op.create_index('idx_org_status', ['status'], unique=False)

    op.create_table('org_org_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_a_id', sa.Integer(), nullable=False),
    sa.Column('org_b_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('period_start', sa.String(), nullable=True),
    sa.Column('period_end', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('reliability_level', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('org_a_id != org_b_id', name='ck_org_org_different'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_a_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['org_b_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_org_links', schema=None) as batch_op:
        batch_op.create_index('idx_ool_org_a', ['org_a_id'], unique=False)
        batch_op.create_index('idx_ool_org_b', ['org_b_id'], unique=False)

    op.create_table('person_org_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('period_start', sa.String(), nullable=True),
    sa.Column('period_end', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('reliability_level', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'org_id', 'link_type', name='uq_person_org_type')
    )
    with op.batch_alter_table('person_org_links', schema=None) as batch_op:
        batch_op.create_index('idx_pol_org', ['org_id'], unique=False)
        batch_op.create_index('idx_pol_person', ['person_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_org_links', schema=None) as batch_op:
        batch_op.drop_index('idx_pol_person')
        batch_op.drop_index('idx_pol_org')

    op.drop_table('person_org_links')
    with op.batch_alter_table('org_org_links', schema=None) as batch_op:
        batch_op.drop_index('idx_ool_org_b')
        batch_op.drop_index('idx_ool_org_a')

    op.drop_table('org_org_links')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index('idx_org_status')
        batch_op.drop_index('idx_org_name')

    op.drop_table('organizations')
    # ### end Alembic commands ###
