"""03-1_incident_reports

Revision ID: 69d13ab45fb9
Revises: at0307_platea_exclude
Create Date: 2026-08-11 15:30:14.903638+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69d13ab45fb9'
down_revision: Union[str, None] = 'at0307_platea_exclude'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('person_role', sa.String(length=50), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('bo_number', sa.String(length=100), nullable=True),
    sa.Column('bo_date', sa.String(length=20), nullable=True),
    sa.Column('issuing_unit', sa.String(length=200), nullable=True),
    sa.Column('criminal_classification', sa.String(length=500), nullable=True),
    sa.Column('procedural_status', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_reports', schema=None) as batch_op:
        batch_op.create_index('idx_incident_reports_case_id', ['case_id'], unique=False)
        batch_op.create_index('idx_incident_reports_person_id', ['person_id'], unique=False)
        batch_op.create_index('idx_incident_reports_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('incident_reports', schema=None) as batch_op:
        batch_op.drop_index('idx_incident_reports_status')
        batch_op.drop_index('idx_incident_reports_person_id')
        batch_op.drop_index('idx_incident_reports_case_id')

    op.drop_table('incident_reports')
    # ### end Alembic commands ###
